### ISSUE TITLE
Sessionにavatarが無かった問題

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#212]
6fe3399 にてmasterにcommitし、とりあえず修正
backendのsession.goには

https://github.com/lc-tut/club-portal/blob/cbd1d66160a71499ffd8bd7e8b1cf575a6ac0590/router/utils/session.go#L3-L22
```
package utils

type SessionData struct {
	SessionUUID string `json:"session_uuid"`
	UserUUID    string `json:"user_uuid"`
	Email       string `json:"email"`
	Name        string `json:"name"`
	Role        string `json:"role"`
	AvatarURL   string `json:"avatar"`
}

func NewSessionData(sessionUUID, userUUID, email, name, role, avatarURL string) *SessionData {
	s := &SessionData{
		SessionUUID: sessionUUID,
		UserUUID:    userUUID,
		Email:       email,
		Name:        name,
		Role:        role,
		AvatarURL:   avatarURL,
	}
	return s
}
```
こんな感じでSessionの中にAvaterURLがあったので、とりあえずfrontendのapi.tsでSession型に `avatar: string` を追加した。

Sessionにavatarを入れなかったことに意図を感じなくもかなったので、一応issueで報告という形を取った。

**Comment by caffeine0coffee** [comment]
言い忘れたが、上記変更では正しく動作している。
ちゃんとアバター画像のURLを取得できた。

**Comment by KashEight** [comment]
あ, 普通に含んでいたのを忘れていた… (OpenAPI の定義のまま型定義行ったからそっちも修正しとかないと)
報告ありがとうございます🙇
