### ISSUE TITLE
ぱんくずリストの実装

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#214]
詳細はPR参照

**Comment by caffeine0coffee** [comment]
リファクタリングが厳しいようならPreviewには含めなくても良いかもね
いうてぱんくずリストだし

現状
![image](https://user-images.githubusercontent.com/48763656/158675446-873801e2-5ded-4010-bb81-fd9e44db0d89.png)

ぱんくずリスト無しバージョン
![image](https://user-images.githubusercontent.com/48763656/158675349-808b8353-9552-4371-8e80-151425cac24a.png)

**Comment by KashEight** [comment]
バージョンアップで色々できるっぽいので新しい Issue たてて対応
