### ISSUE TITLE
活動日に「平日」「休日」を追加する

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#221]
# 概要

現状、 `PlaceAndTimeEditor` においては活動日を「月」〜「日」の曜日のみで扱っているが、これに「平日」と「休日」を追加したい

# 詳細

サークルパンフレット・ClubPortalの情報収集Formにおいて、活動日時と活動場所はパンフレットとClubPortalの間で共通する情報だった。
従って「曜日と時間のリストで回答して下さい」といった指定をしていなかった。（その部分のForm作成は青木さんが担当した）
その結果、「平日はOO時からやります」といった数多くあり、それに対応するためにも表題の通り「平日」・「休日」を追加する必要があると考えた。

例 Jacla
```
平　日  19:00 ~ 21:00
土曜日    9:00 ~ 19:00
```

例: サウンドジェネシス
```
平日 19：00〜20：00
```

例: 化学サークル
```
週 １～２ 月～金　18:45　(連絡します)
```
↑これは備考との組み合わせで表現できそう

**Comment by caffeine0coffee** [comment]
化学サークルの「月～金　18:45」を「平日 18:45」にするのが良くないってことですかね...？
個人的には
```
月: 18:45 ~ 21:00
火: 18:45 ~ 21:00
水: 18:45 ~ 21:00
```
や
```
活動時間・場所　　その他
備考　月〜金 18:45で活動します
```
って表示するよりも
```
平日: 18:45 ~ 21:00
```
って表示したほうがスッキリすると思ったので、これで良いと思っています。
「月〜金」と「平日」では、祝日なども考慮した場合に厳密には異なってしまうという話ですか？

パンフレットの記載と共通化するべきなのは理解できますが、ClubPortalでは表示の形式が制限されているので（対してパンフレットは「活動時間: (任意の文字列)」なので融通が効く）多少は仕方ないとも思います。

まあ化学サークルみたいな表記はともかく、Jaclaなどは「平日」というように表記しているので、表題の通り「平日」を選択肢に加えるのは取り敢えずアリなのではないでしょうか。

**Comment by KashEight** [comment]
一応, 平日という表記 (Jacla, サウジェ) を月～金にするとどういう感じになるか意見が欲しかった感じですね…

確かに, 見えづらさ考えると "平日" という選択肢は入れといてはいいかなとは (個人的には) 思います. 問題は "平日" の適用範囲をどこまでにするかかなあぐらいかなと.

あとは, 休日は 2 日しかないのと, かなり例外的なものなので追加するなら平日だけでいいかなと思いました.

**Comment by caffeine0coffee** [comment]
あ〜！！そういうことでしたか！
ニュアンスの理解ができず、申し訳ないです:bow:

> 一応, 平日という表記 (Jacla, サウジェ) を月～金にするとどういう感じになるか意見が欲しかった感じですね…

それもアリ...正直どちらも良いと思います。
ただ、祝日で学校が無いのにも関わらず活動をするサークルもあまり無いように思えるので、「祝日でも活動します」というニュアンスがある程度排除できる「平日」で良いんじゃないかと考えます。

> 確かに, 見えづらさ考えると "平日" という選択肢は入れといてはいいかなとは (個人的には) 思います. 問題は "平日" の適用範囲をどこまでにするかかなあぐらいかなと.

確かに難しいところではありますが、Formに「平日」や「月〜金」と書いているサークル側もあんまり深くは考えてなさそう...
まあClubPortalが連絡手段の全てではないので、厳密に定義する必要も無いと考えています。

> あとは, 休日は 2 日しかないのと, かなり例外的なものなので追加するなら平日だけでいいかなと思いました.

こちらは同意です。
どちらでも良いとも思いますが、その意見に特に異議も無いので「『休日』は追加しない」の方向で大丈夫だと思います。

**Comment by KashEight** [comment]
了解しました！

とりあえず, "平日" のみ追加する形で実装したいと思います～.

**Comment by caffeine0coffee** [comment]
お願いします！
