### ISSUE TITLE
ValidSNSに追加するもの

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#222]
# 概要

パンフレット・ClubPortal情報収集Formを整理した上で、新たに必要だと感じたValidSNS

# 詳細

現状の `SNSLinkEditor` と `ClubDescription` においては、`twitter` と `instagram` のみがValidSNSとして登録されている。
これに加えて、以下のSNS(?)も追加したい。

- YouTube
- Line
- Blog
- Discord

YouTubeについては、チャンネルURLを記載したサークルがあった。

Lineについては、Lineオープンチャットのリンクを記載したサークルが1件あった。これについてはLineのリンクとして扱っていいんじゃないかと思っている。

**Comment by KashEight** [comment]
そこまで複雑な実装はいらないと思うのですぐできるとは思います. 
最悪, 後でリリース後に追加でも対応は可能かと.

**Comment by caffeine0coffee** [comment]
bb4dd9dfe34dd4c01ea709f6d4b3704a1bd6ae62 にて対応済み
「Blog」に関してはいらないかなと思ったので追加していない
