### ISSUE TITLE
Preview公開後のTODO

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#256]
随時コメントなどで追加して下さい

# 至急対応

- [x] `ClubPageInternal` の情報も含めたサークル検索
- [x] HPをアンカー化する

↓これ
![image](https://user-images.githubusercontent.com/48763656/158979183-8cff2699-0207-4b52-ba2b-4c035c7cfbed.png)

- [x] FireFoxにおける紹介ページバグの解消

# 順次対応

## 全体

- [x] スマホ向けレイアウトの実装
- [ ] ぱんくずリストの実装
- [x] 蒲田版のサークル紹介サイトのURLを掲載する
- [x] favicon の追加

## 編集者ページ

- [ ] Adminユーザーが任意のサークルを編集できるようにする
- [x] 編集者ページで「保存」を押して成功したらトーストを出す
- [ ] 紹介動画を削除できるようにする
- [x] IconEditorで既に設定されたアイコンを表示するようにする

現状は `default.png` になってしまう
![image](https://user-images.githubusercontent.com/48763656/158961379-96b8bcf7-ed1c-4324-9eef-3ac92fb31a1c.png)

- [x] DetailEditorで「曜日を「その他」にする」をONにした状態で追加できない不具合を修正する

この状態で+(plus)ボタンを押しても追加されない
![image](https://user-images.githubusercontent.com/48763656/158961589-01812b9e-4ff7-4937-b042-90bc29dfbae7.png)

**Comment by caffeine0coffee** [comment]
## 青木さんからの返信

これは青木さんから頂いたFBです。
リリースの旨を伝えたら秒で返信来ました。

> 気になる点としましては、
検索キーワードで「バドミントン」と検索したところ、
バドミントン部しか出てこなかったです。アミーゴもバドミントンサークルなのでヒットしてほしかったです。
私の推測ですが、一言コメントにしか検索キーワードはヒットしない仕様ですか？
もしそうであれば、クリックした先の詳細からも検索キーワードとしてヒットしてほしいなと思いました。
> あと、各サークルのHPの記載ですが、クリックすればホームページへ飛ぶ仕様のの方がいいかなと思いました。

**Comment by caffeine0coffee** [comment]
> HPをアンカー化する

URLが絶対パスじゃないとClubPortalの相対パスとして扱われてしまう
丁度スクショに載っている [advancedcreators.undo.jp/](advancedcreators.undo.jp/) で不具合が起こってしまう（てかこのコメントのリンクを踏んでも `https://github.com/lc-tut/club-portal-frontend/issues/advancedcreators.undo.jp/` に飛ぶわ）

リリース直後ではアドバンのリンクのみが相対リンクなのでそれを直す必要がある
編集者ページでも絶対パスのみ受け付けるようにする必要がある

**Comment by KashEight** [comment]
詳細情報やリンクの編集では, 一気に追加, 削除して API を叩く処理にしているが, 随時 API 叩く処理に変更したい (現状コードがかなり複雑となっておりバグの温床になっている)

**Comment by caffeine0coffee** [comment]
とはいえ明日(3/23)開催される対面でのリーキャンでClubPortalのアナウンスがされるので、最低限まともに動作するものを取り敢えず用意したい

**Comment by KashEight** [comment]
Search API 実装したのでサークル検索実装できるかと思います (遅くなり申し訳ないです)
https://github.com/lc-tut/club-portal/pull/49

**Comment by caffeine0coffee** [comment]
早くね
ありがとう！
frontendの実装を試してみます

**Comment by KashEight** [comment]
残ったものは #284 に移したので Close
