### ISSUE TITLE
画像を0枚にすることができない

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#269]
ImageEditorにおいて、全ての画像を削除してから「保存」を押しても反映されない（つまり、掲載画像が0枚にならない）
frontendでは「成功」のトーストが出る

draft PR #266 で再現可能

**Comment by KashEight** [comment]
https://github.com/lc-tut/club-portal/commit/171ad5ba5cb137d6d1053663594608b3f0bcbd07 にて修正
