### ISSUE TITLE
スクロール位置が遷移前のページと同じになる

### ISSUE THREAD

**Issue by 6mile0** [lc-tut/club-portal-frontend#287]
本番環境で確認していたところ，サークル詳細画面に遷移した後のスクロール位置がサークルによって違う点が気になりました。

https://user-images.githubusercontent.com/39295293/187579381-5446522d-2379-4e8f-a362-09838d34cf50.mp4

**Comment by 6mile0** [comment]
スクロール位置をリセットするコンポーネントを作ると良い感じですかね？

**Comment by caffeine0coffee** [comment]
なるほど、確かにスクロール位置がリセットされてないですね
今まで気づかなかった箇所です...
正直、私もパッとは解決策が思い浮かばないのですが、軽く調べたところ `react-router-dom` モジュールの `useHistory` HookでURLの変更を監視し、`window.scrollTo()` を用いて位置をリセットする方法があるようです。
https://chaika.hatenablog.com/entry/2020/04/23/113000
`react-router-dom` は既にインストールされているので、新たに `yarn install` する必要はありません

新たなコンポーネントなどは作っていただいて構いません！
ただ、その際は新しくブランチを作成してほしいです

**Comment by caffeine0coffee** [comment]
また、開発環境下でもサークル一覧を表示するための準備（具体的にはSQLダンプと画像一式）を Kash/Hytus にお願いしているところです
もう少々お待ちくださいmm

**Comment by 6mile0** [comment]
承知しました！
とりあえずアセット類の準備ができるまでお待ちしております

**Comment by 6mile0** [comment]
> `react-router-dom` モジュールの `useHistory Hook`でURLの変更を監視し、`window.scrollTo()` を用いて位置をリセットする方法があるようです。

`useHistory Hook` 自体が `react-router-dom` v5までの書き方でしたので, `react-router-dom` v6の `Location`を `useEffect`で監視してスクロール量を0にする方法で実装しました.
早々にアセット類の用意をしていただいたのに遅くなってしまい申し訳ありません.

**Comment by KashEight** [comment]
fixed #290
