### ISSUE TITLE
使用する色に名前を付けて定義したい

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal-frontend#3]
# 概要

現段階ではトップページしか作成されていないが、これから作るサークル一覧ページ等にはChakra UIで定義されたもの以外に多くの色を使う。
それらはAdobeXDのワイヤーフレーム内で`text_main`や`text_sub`, `form_background`等の名前が付けられているので、ソースコード内でも同様の名前で色を定義したい。

# 考えられる方法

Chakra UIのThemeを拡張することでユーザー定義の色を使いやすくできる。
参考 : https://chakra-ui.com/docs/theming/customize-theme
リンク先のコードを`app.tsx`にコピーして`<ChakraProvider>`に属性を追加することで安直に実装できそうだが、ユーザー定義の色が未整理のものも含めて19個くらいあるので`app.tsx`にコピペして良いものか...
色の定義は別のモジュールでやったほうが見通しも良さそうだし...
このリポジトリのディレクトリごとのニュアンス等もなんとなくでしか理解できていないので何を何処に作成すれば良いか教えて欲しい。

おしえてぶちょー

**Comment by KashEight** [comment]
そこらへん自分もいじってないから試してやるしかなさげではありそう…

**Comment by caffeine0coffee** [comment]
OKですー
ある程度自己判断でファイルやらディレクトリやら作っちゃうのでPR時にレビューお願いしやす
