### ISSUE TITLE
外部リンクを追加すると連絡先のメールアドレス欄に記載したメールアドレスが消える、又は逆の現象

### ISSUE THREAD

**Issue by Mikuto0831** [lc-tut/club-portal-frontend#788]
本日案内していただいたクラブポータルサイトについて、不具合が見受けられました。

おそらくLinux Clubさんが作成しているものだと認識しているのですが、不具合報告についてはそちらに直接送付した方がいいでしょうか。

学務課の管理下にあるのかどうか不明なため、一度こちらに連絡させていただいた次第です。

 

具体的な不具合については、以下の通りです。

 

・外部リンクとメールアドレスの競合

編集者メニューにある「外部リンクの編集」から外部リンクを追加すると、「詳細情報の編集」から記載可能な「連絡先のメールアドレス」欄に記載したメールアドレスが消える。メールアドレスを入力し更新すると、外部リンクが全て消えるため、どちらか片方しか入力できない。

動作環境はMac mini M4、MacOS 15.1.1、Google Chrome 131.0.6778.86(Official Build) (arm64)

**Comment by Mikuto0831** [comment]
まずは検証します

**Comment by Mikuto0831** [comment]
いずれかを更新すると表示されていたデータが消える現象を確認しました
![image](https://github.com/user-attachments/assets/85b0546e-0d84-4c7a-a227-40886fad0902)

**Comment by Mikuto0831** [comment]
バックエンド側で問題となる箇所を見つけたためそちらからアプローチします。

**Comment by Mikuto0831** [comment]
以下の部分でメールアドレスの除外又は抽出をしているが、ユーザの目に見える直前でメールアドレスの除外又は抽出をするように変更すれば解決できる
という変更を提案するのですがいかがでしょうか？ @KashEight 

https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/components/common/Editor/DetailLinkEditor.tsx#L44 
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/components/common/Editor/DetailLinkEditor.tsx#L48-L54 
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/pages/editor/link.tsx#L52
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/pages/editor/link.tsx#L59-L122

**Comment by KashEight** [comment]
> 以下の部分でメールアドレスの除外又は抽出をしているが、ユーザの目に見える直前でメールアドレスの除外又は抽出をするように変更すれば解決できる

既に `useAPI()` で必要なデータはバックエンドから全て抽出 (fetch) して、`useEffect()` 上で目に見える部分はフィルターしているので、PUT リクエストを送信するときに (`label: email`, `label: email 以外` も含んだ) 既存のデータを含ませるのが解決法になりますね

email での `useAPI()` と `useEffect()`:
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/components/common/Editor/DetailLinkEditor.tsx#L43
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/components/common/Editor/DetailLinkEditor.tsx#L48-L54

link での `useAPI()` と `useEffect()`:   
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/pages/editor/link.tsx#L42
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/pages/editor/link.tsx#L59-L64

本来は、更新するデータ + 既存のデータを Payload として渡す必要があるのが、更新分のみしか渡されてないのがバグの原因となっている感じです

email における該当箇所:
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/components/common/Editor/DetailLinkEditor.tsx#L57-L62

link における該当箇所:
https://github.com/lc-tut/club-portal-frontend/blob/e3e9ef56f89db77bc4154c56671a846c55740150/src/pages/editor/link.tsx#L67-L72
